# Generated by Django 4.1.3 on 2023-02-08 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название чата')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата отправки сообщения')),
                ('user', models.CharField(max_length=1000)),
                ('room', models.ManyToManyField(to='chatApp.room')),
            ],
        ),
    ]
