# Generated by Django 4.1.3 on 2023-02-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_remove_message_room_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000000, null=True, verbose_name='Текст сообщения'),
        ),
    ]
