# Generated by Django 4.1.3 on 2023-02-08 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 9, 0, 22, 18, 379089), verbose_name='Дата отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000, null=True, verbose_name='Текст сообщения'),
        ),
    ]
